sudo: false
language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.7
  - 2.2.1
  - 2.2.3
  - 2.3.1
before_install: gem install bundler -v 1.13.6
addons:
    code_climate:
        repo_token: dcdb2b8d67dad3b794f81cdb25ec5c016b677002fadb5296f8ae12c00c789cb8
